# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Backup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mangabackup.tachiyomi.models.BackupManga_pb2 as BackupManga__pb2
import mangabackup.tachiyomi.models.BackupCategory_pb2 as BackupCategory__pb2
import mangabackup.tachiyomi.models.BackupSource_pb2 as BackupSource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x42\x61\x63kup.proto\x1a\x11\x42\x61\x63kupManga.proto\x1a\x14\x42\x61\x63kupCategory.proto\x1a\x12\x42\x61\x63kupSource.proto\"|\n\x06\x42\x61\x63kup\x12!\n\x0b\x62\x61\x63kupManga\x18\x01 \x03(\x0b\x32\x0c.BackupManga\x12)\n\x10\x62\x61\x63kupCategories\x18\x02 \x03(\x0b\x32\x0f.BackupCategory\x12$\n\rbackupSources\x18\x65 \x03(\x0b\x32\r.BackupSourceb\x06proto3')



_BACKUP = DESCRIPTOR.message_types_by_name['Backup']
Backup = _reflection.GeneratedProtocolMessageType('Backup', (_message.Message,), {
  'DESCRIPTOR' : _BACKUP,
  '__module__' : 'Backup_pb2'
  # @@protoc_insertion_point(class_scope:Backup)
  })
_sym_db.RegisterMessage(Backup)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKUP._serialized_start=77
  _BACKUP._serialized_end=201
# @@protoc_insertion_point(module_scope)
