# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BackupSource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x42\x61\x63kupSource.proto\".\n\x0c\x42\x61\x63kupSource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08sourceId\x18\x02 \x01(\x03\x62\x06proto3')



_BACKUPSOURCE = DESCRIPTOR.message_types_by_name['BackupSource']
BackupSource = _reflection.GeneratedProtocolMessageType('BackupSource', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPSOURCE,
  '__module__' : 'BackupSource_pb2'
  # @@protoc_insertion_point(class_scope:BackupSource)
  })
_sym_db.RegisterMessage(BackupSource)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKUPSOURCE._serialized_start=22
  _BACKUPSOURCE._serialized_end=68
# @@protoc_insertion_point(module_scope)
