# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BackupTracking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42\x61\x63kupTracking.proto\"\xf0\x01\n\x0e\x42\x61\x63kupTracking\x12\x0e\n\x06syncId\x18\x01 \x01(\x05\x12\x11\n\tlibraryId\x18\x02 \x01(\x03\x12\x0f\n\x07mediaId\x18\x03 \x01(\x05\x12\x13\n\x0btrackingUrl\x18\x04 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\x12\x17\n\x0flastChapterRead\x18\x06 \x01(\x02\x12\x15\n\rtotalChapters\x18\x07 \x01(\x05\x12\r\n\x05score\x18\x08 \x01(\x02\x12\x0e\n\x06status\x18\t \x01(\x05\x12\x1a\n\x12startedReadingDate\x18\n \x01(\x03\x12\x1b\n\x13\x66inishedReadingDate\x18\x0b \x01(\x03\x62\x06proto3')



_BACKUPTRACKING = DESCRIPTOR.message_types_by_name['BackupTracking']
BackupTracking = _reflection.GeneratedProtocolMessageType('BackupTracking', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPTRACKING,
  '__module__' : 'BackupTracking_pb2'
  # @@protoc_insertion_point(class_scope:BackupTracking)
  })
_sym_db.RegisterMessage(BackupTracking)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKUPTRACKING._serialized_start=25
  _BACKUPTRACKING._serialized_end=265
# @@protoc_insertion_point(module_scope)
