# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BackupManga.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mangabackup.tachiyomi.models.BackupChapter_pb2 as BackupChapter__pb2
import mangabackup.tachiyomi.models.BackupTracking_pb2 as BackupTracking__pb2
import mangabackup.tachiyomi.models.BackupHistory_pb2 as BackupHistory__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42\x61\x63kupManga.proto\x1a\x13\x42\x61\x63kupChapter.proto\x1a\x14\x42\x61\x63kupTracking.proto\x1a\x13\x42\x61\x63kupHistory.proto\"\xdf\x03\n\x0b\x42\x61\x63kupManga\x12\x0e\n\x06source\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x06\x61rtist\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\r\n\x05genre\x18\x07 \x03(\t\x12\x0e\n\x06status\x18\x08 \x01(\x05\x12\x19\n\x0cthumbnailUrl\x18\t \x01(\tH\x03\x88\x01\x01\x12\x11\n\tdateAdded\x18\r \x01(\x03\x12\x0e\n\x06viewer\x18\x0e \x01(\x05\x12 \n\x08\x63hapters\x18\x10 \x03(\x0b\x32\x0e.BackupChapter\x12\x12\n\ncategories\x18\x11 \x03(\x05\x12!\n\x08tracking\x18\x12 \x03(\x0b\x32\x0f.BackupTracking\x12\x10\n\x08\x66\x61vorite\x18\x64 \x01(\x08\x12\x14\n\x0c\x63hapterFlags\x18\x65 \x01(\x05\x12\x19\n\x0cviewer_flags\x18g \x01(\x05H\x04\x88\x01\x01\x12\x1f\n\x07history\x18h \x03(\x0b\x32\x0e.BackupHistoryB\t\n\x07_artistB\t\n\x07_authorB\x0e\n\x0c_descriptionB\x0f\n\r_thumbnailUrlB\x0f\n\r_viewer_flagsb\x06proto3')



_BACKUPMANGA = DESCRIPTOR.message_types_by_name['BackupManga']
BackupManga = _reflection.GeneratedProtocolMessageType('BackupManga', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPMANGA,
  '__module__' : 'BackupManga_pb2'
  # @@protoc_insertion_point(class_scope:BackupManga)
  })
_sym_db.RegisterMessage(BackupManga)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKUPMANGA._serialized_start=86
  _BACKUPMANGA._serialized_end=565
# @@protoc_insertion_point(module_scope)
