# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BackupHistory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x42\x61\x63kupHistory.proto\".\n\rBackupHistory\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08lastRead\x18\x02 \x01(\x03\x62\x06proto3')



_BACKUPHISTORY = DESCRIPTOR.message_types_by_name['BackupHistory']
BackupHistory = _reflection.GeneratedProtocolMessageType('BackupHistory', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPHISTORY,
  '__module__' : 'BackupHistory_pb2'
  # @@protoc_insertion_point(class_scope:BackupHistory)
  })
_sym_db.RegisterMessage(BackupHistory)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKUPHISTORY._serialized_start=23
  _BACKUPHISTORY._serialized_end=69
# @@protoc_insertion_point(module_scope)
