# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BackupCategory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42\x61\x63kupCategory.proto\"<\n\x0e\x42\x61\x63kupCategory\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05order\x18\x02 \x01(\x05\x12\r\n\x05\x66lags\x18\x64 \x01(\x05\x62\x06proto3')



_BACKUPCATEGORY = DESCRIPTOR.message_types_by_name['BackupCategory']
BackupCategory = _reflection.GeneratedProtocolMessageType('BackupCategory', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPCATEGORY,
  '__module__' : 'BackupCategory_pb2'
  # @@protoc_insertion_point(class_scope:BackupCategory)
  })
_sym_db.RegisterMessage(BackupCategory)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKUPCATEGORY._serialized_start=24
  _BACKUPCATEGORY._serialized_end=84
# @@protoc_insertion_point(module_scope)
